import { Montserrat } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/Navigation";

const montserrat = Montserrat({ 
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-Montserrat",
});

export const metadata = {
  title: "CIT-U Electoral System",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={montserrat.variable}>
				<Navigation/>
				{children}
			</body>
		</html>
	);
}
