import { Montserrat } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Sidebar from "@/components/dashboard-components/Sidebar";
import DashboardNav from "@/components/dashboard-components/DashboardNav";


const montserrat = Montserrat({ 
	subsets: ["latin"],
	weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
	variable: "--font-Montserrat",
});

export const metadata = {
	title: "CIT-U Electoral System",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {

	const isLoggedin = true;
	
	return (
		<html lang="en">
			<body className={montserrat.variable}>
				{isLoggedin ? <DashboardNav/>: <Header/>}
				
				{children}

				{isLoggedin ? '' : <Footer/>}
				
			</body>
		</html>
	);
}
